//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGISControl.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_ArcGISControl_ArcGISClientViewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ArcGISControl_ArcGISClientViewer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGISControl.Language.Resource.ArcGISControl.ArcGISClientViewer", typeof(Resource_ArcGISControl_ArcGISClientViewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Const_DefaultNameFormat_Location {
            get {
                return ResourceManager.GetString("Const_DefaultNameFormat_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookMark.
        /// </summary>
        public static string Const_DefaultNamePrefix_BookMark {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_BookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Const_DefaultNamePrefix_Image {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Const_DefaultNamePrefix_Line {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkZone.
        /// </summary>
        public static string Const_DefaultNamePrefix_LinkZone {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_LinkZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Const_DefaultNamePrefix_Location {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Const_DefaultNamePrefix_Text {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Const_DefaultNamePrefix_Unknown {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkStation.
        /// </summary>
        public static string Const_DefaultNamePrefix_WorkStation {
            get {
                return ResourceManager.GetString("Const_DefaultNamePrefix_WorkStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected backup file is ONLY for the map with guid {0}, but the guid of the current map is {1}. Should I apply it anyway?.
        /// </summary>
        public static string Message_AskApplyingWrongBackup {
            get {
                return ResourceManager.GetString("Message_AskApplyingWrongBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a map named {0}.
        /// </summary>
        public static string Message_CanNotFindMapName_LinkedMap {
            get {
                return ResourceManager.GetString("Message_CanNotFindMapName_LinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load Customtile.
        /// </summary>
        public static string Message_CanNotLoadCustomTile {
            get {
                return ResourceManager.GetString("Message_CanNotLoadCustomTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load map. Please check log message..
        /// </summary>
        public static string Message_CanNotLoadMap {
            get {
                return ResourceManager.GetString("Message_CanNotLoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Make LinkZone. Please make more 3 Points.
        /// </summary>
        public static string Message_CanNotMakeLinzone_Less3Points {
            get {
                return ResourceManager.GetString("Message_CanNotMakeLinzone_Less3Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Show Linked Map By Current User.
        /// </summary>
        public static string Message_CanNotShowLinkedMap {
            get {
                return ResourceManager.GetString("Message_CanNotShowLinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Show Popup.
        /// </summary>
        public static string Message_CanNotShowPopup {
            get {
                return ResourceManager.GetString("Message_CanNotShowPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not have Link on the Map.
        /// </summary>
        public static string Message_DidNotSetLinkedMap {
            get {
                return ResourceManager.GetString("Message_DidNotSetLinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not have permission..
        /// </summary>
        public static string Message_DoesNotHavePermission {
            get {
                return ResourceManager.GetString("Message_DoesNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ill-formed latitude-longitude format received: {0}.
        /// </summary>
        public static string Message_IllFormedLineToData {
            get {
                return ResourceManager.GetString("Message_IllFormedLineToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ill-formed map name list recieved: {0}.
        /// </summary>
        public static string Message_IllFormedLinkedMapData {
            get {
                return ResourceManager.GetString("Message_IllFormedLinkedMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Backup File.
        /// </summary>
        public static string Message_InvalidBackupFile {
            get {
                return ResourceManager.GetString("Message_InvalidBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map KEY or URL is not allowed. Please check out KEY or URL.
        /// </summary>
        public static string Message_MapKeyNotAllowed {
            get {
                return ResourceManager.GetString("Message_MapKeyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Url is empty.
        /// </summary>
        public static string Message_MapNullUrl {
            get {
                return ResourceManager.GetString("Message_MapNullUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data can&apos;t loaded..
        /// </summary>
        public static string Message_MapSplFail {
            get {
                return ResourceManager.GetString("Message_MapSplFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Message_MapSplLoading {
            get {
                return ResourceManager.GetString("Message_MapSplLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health data not found..
        /// </summary>
        public static string Message_MapSplNoResult {
            get {
                return ResourceManager.GetString("Message_MapSplNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string Message_Splunk_No_Result {
            get {
                return ResourceManager.GetString("Message_Splunk_No_Result", resourceCulture);
            }
        }
    }
}
