//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGISControl.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_ArcGISControl_Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ArcGISControl_Properties() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGISControl.Language.Resource.ArcGISControl.Properties", typeof(Resource_ArcGISControl_Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   APPLY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BUTTON_APPLY {
            get {
                return ResourceManager.GetString("BUTTON_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BROWSE...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE CURRENT LEVEL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_SetCurrentLevel {
            get {
                return ResourceManager.GetString("Button_SetCurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckBox_Splunk_HideIcon {
            get {
                return ResourceManager.GetString("CheckBox_Splunk_HideIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show X Axis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckBox_Splunk_ShowXAxis {
            get {
                return ResourceManager.GetString("CheckBox_Splunk_ShowXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckBox_Splunk_UpdateInterval {
            get {
                return ResourceManager.GetString("CheckBox_Splunk_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMPORT IMAGE(S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImportImageCommand {
            get {
                return ResourceManager.GetString("ImportImageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAMERA ICON A과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Item_CameraIcon_A {
            get {
                return ResourceManager.GetString("Item_CameraIcon_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Item_Hide {
            get {
                return ResourceManager.GetString("Item_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visible과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Item_Visible {
            get {
                return ResourceManager.GetString("Item_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AlwaysKeepToCameraVideo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AlwaysKeepToCameraVideo {
            get {
                return ResourceManager.GetString("Label_AlwaysKeepToCameraVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AutoRange {
            get {
                return ResourceManager.GetString("Label_AutoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraIcon {
            get {
                return ResourceManager.GetString("Label_CameraIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Visibility :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraIcon_Visibility {
            get {
                return ResourceManager.GetString("Label_CameraIcon_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraIconSize {
            get {
                return ResourceManager.GetString("Label_CameraIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraIconSize_Max {
            get {
                return ResourceManager.GetString("Label_CameraIconSize_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraIconSize_Min {
            get {
                return ResourceManager.GetString("Label_CameraIconSize_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraIconSize_Normal {
            get {
                return ResourceManager.GetString("Label_CameraIconSize_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraName {
            get {
                return ResourceManager.GetString("Label_CameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraPreset {
            get {
                return ResourceManager.GetString("Label_CameraPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constrain Proportion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraVideoConstrainProportion {
            get {
                return ResourceManager.GetString("Label_CameraVideoConstrainProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video not displayed after next zoom in level :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraVideoHiddenMaxLevel {
            get {
                return ResourceManager.GetString("Label_CameraVideoHiddenMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video not displayed after next zoom out level :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraVideoHiddenMinLevel {
            get {
                return ResourceManager.GetString("Label_CameraVideoHiddenMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock Position &amp; Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraVideoLockPositionAndSize {
            get {
                return ResourceManager.GetString("Label_CameraVideoLockPositionAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom in not operational after preset level :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CameraVideoScaleMaxLevel {
            get {
                return ResourceManager.GetString("Label_CameraVideoScaleMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color SPL :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ColorSplunkInformationData {
            get {
                return ResourceManager.GetString("Label_ColorSplunkInformationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy-MM-dd HH:mm:ss (case-sensitive)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DateFormatGuideMessage {
            get {
                return ResourceManager.GetString("Label_DateFormatGuideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date  
        ///Format :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DateTimeFormat {
            get {
                return ResourceManager.GetString("Label_DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FillColor {
            get {
                return ResourceManager.GetString("Label_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Default Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LegendUseGlobalSetting {
            get {
                return ResourceManager.GetString("Label_LegendUseGlobalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arrow End :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Arrow_End {
            get {
                return ResourceManager.GetString("Label_Line_Arrow_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arrow End Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Arrow_End_Size {
            get {
                return ResourceManager.GetString("Label_Line_Arrow_End_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arrow Start :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Arrow_Start {
            get {
                return ResourceManager.GetString("Label_Line_Arrow_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arrow Start Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Arrow_Start_Size {
            get {
                return ResourceManager.GetString("Label_Line_Arrow_Start_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Color {
            get {
                return ResourceManager.GetString("Label_Line_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Line Cap :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_End_Cap {
            get {
                return ResourceManager.GetString("Label_Line_End_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock Position &amp; Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Lock_Position {
            get {
                return ResourceManager.GetString("Label_Line_Lock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Line Cap :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Start_Cap {
            get {
                return ResourceManager.GetString("Label_Line_Start_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stroke :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Stroke {
            get {
                return ResourceManager.GetString("Label_Line_Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stroke Line Join :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_Stroke_Line_Join {
            get {
                return ResourceManager.GetString("Label_Line_Stroke_Line_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stroke Thickness :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Line_StrokeThickness {
            get {
                return ResourceManager.GetString("Label_Line_StrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linked Map :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LinkedMap {
            get {
                return ResourceManager.GetString("Label_LinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BookMark :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LinkedMapBookMark {
            get {
                return ResourceManager.GetString("Label_LinkedMapBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageName :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LinkZoneImageName {
            get {
                return ResourceManager.GetString("Label_LinkZoneImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LinkZoneName {
            get {
                return ResourceManager.GetString("Label_LinkZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LinkZoneName1 {
            get {
                return ResourceManager.GetString("Label_LinkZoneName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAP LEVEL :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_MapLevel {
            get {
                return ResourceManager.GetString("Label_MapLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outline :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OutlineColor {
            get {
                return ResourceManager.GetString("Label_OutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Address :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_PlaceAddress {
            get {
                return ResourceManager.GetString("Label_PlaceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_PlaceIconSize {
            get {
                return ResourceManager.GetString("Label_PlaceIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_PlaceName {
            get {
                return ResourceManager.GetString("Label_PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_PlaceValue {
            get {
                return ResourceManager.GetString("Label_PlaceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Search Argument과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkArgument {
            get {
                return ResourceManager.GetString("Label_SplunkArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X-axis :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkChartAxisXTitle {
            get {
                return ResourceManager.GetString("Label_SplunkChartAxisXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y-axis :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkChartAxisYTitle {
            get {
                return ResourceManager.GetString("Label_SplunkChartAxisYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legend Font Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkChartLegendFontSize {
            get {
                return ResourceManager.GetString("Label_SplunkChartLegendFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legend Size (%):과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkChartLegendSize {
            get {
                return ResourceManager.GetString("Label_SplunkChartLegendSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y max :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkChartYAxisRangeMax {
            get {
                return ResourceManager.GetString("Label_SplunkChartYAxisRangeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y min :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkChartYAxisRangeMin {
            get {
                return ResourceManager.GetString("Label_SplunkChartYAxisRangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constrain Proportion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkConstrainProportion {
            get {
                return ResourceManager.GetString("Label_SplunkConstrainProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data not displayed after next zoom in level :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkHiddenMaxLevel {
            get {
                return ResourceManager.GetString("Label_SplunkHiddenMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data not displayed after next zoom out level :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkHiddenMinLevel {
            get {
                return ResourceManager.GetString("Label_SplunkHiddenMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link URL :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkLinkUrl {
            get {
                return ResourceManager.GetString("Label_SplunkLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkName {
            get {
                return ResourceManager.GetString("Label_SplunkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SplunkTitle {
            get {
                return ResourceManager.GetString("Label_SplunkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table SPL :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableSplunkInformationData {
            get {
                return ResourceManager.GetString("Label_TableSplunkInformationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Align {
            get {
                return ResourceManager.GetString("Label_Text_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_BackgroundColor {
            get {
                return ResourceManager.GetString("Label_Text_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Checkbox_Bold {
            get {
                return ResourceManager.GetString("Label_Text_Checkbox_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Checkbox_Italic {
            get {
                return ResourceManager.GetString("Label_Text_Checkbox_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Checkbox_Underline {
            get {
                return ResourceManager.GetString("Label_Text_Checkbox_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Combo_Bottom {
            get {
                return ResourceManager.GetString("Label_Text_Combo_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Combo_Center {
            get {
                return ResourceManager.GetString("Label_Text_Combo_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Combo_Left {
            get {
                return ResourceManager.GetString("Label_Text_Combo_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Combo_Right {
            get {
                return ResourceManager.GetString("Label_Text_Combo_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Combo_Top {
            get {
                return ResourceManager.GetString("Label_Text_Combo_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Combo_Vertical_Center {
            get {
                return ResourceManager.GetString("Label_Text_Combo_Vertical_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Font {
            get {
                return ResourceManager.GetString("Label_Text_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Color :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_FontColor {
            get {
                return ResourceManager.GetString("Label_Text_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_FontSize {
            get {
                return ResourceManager.GetString("Label_Text_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock to Screen &amp; Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_LockToScreen {
            get {
                return ResourceManager.GetString("Label_Text_LockToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical Align :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text_Vertical_Align {
            get {
                return ResourceManager.GetString("Label_Text_Vertical_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_BorderFill {
            get {
                return ResourceManager.GetString("Label_UniversalObject_BorderFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Url :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_BorderImageUrl {
            get {
                return ResourceManager.GetString("Label_UniversalObject_BorderImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outline :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_BorderOutline {
            get {
                return ResourceManager.GetString("Label_UniversalObject_BorderOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radius :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_BorderRadius {
            get {
                return ResourceManager.GetString("Label_UniversalObject_BorderRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thickness :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_BorderThickness {
            get {
                return ResourceManager.GetString("Label_UniversalObject_BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconGroup {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Url :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconUrl {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Max :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconXMaxPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconXMaxPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Min :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconXMinPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconXMinPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y Max :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconYMaxPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconYMaxPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y Min :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_IconYMinPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_IconYMinPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampColor {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diameter :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampDiameter {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Lamp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampGroup {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Lamp Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Alarm Lamp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampUse {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampXPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampXPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LampYPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LampYPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmark :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LinkedBookmark {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LinkedBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LinkedMap {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LinkedObject {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LinkedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LinkGroup {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LinkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Url :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_LinkUrl {
            get {
                return ResourceManager.GetString("Label_UniversalObject_LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mapping ID :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_MappingId {
            get {
                return ResourceManager.GetString("Label_UniversalObject_MappingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_Name {
            get {
                return ResourceManager.GetString("Label_UniversalObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shape과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_ShapeGroup {
            get {
                return ResourceManager.GetString("Label_UniversalObject_ShapeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H-Pipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_ShapeHorizontalPipe {
            get {
                return ResourceManager.GetString("Label_UniversalObject_ShapeHorizontalPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_ShapeImage {
            get {
                return ResourceManager.GetString("Label_UniversalObject_ShapeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_ShapeRectangle {
            get {
                return ResourceManager.GetString("Label_UniversalObject_ShapeRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   V-Pipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_ShapeVerticalPipe {
            get {
                return ResourceManager.GetString("Label_UniversalObject_ShapeVerticalPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_Title {
            get {
                return ResourceManager.GetString("Label_UniversalObject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Color :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitleFontColor {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitleFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitleGroup {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitlePos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitlePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Max :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitleXMaxPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitleXMaxPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Min :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitleXMinPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitleXMinPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y Max:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitleYMaxPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitleYMaxPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y Min :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UniversalObject_TitleYMinPos {
            get {
                return ResourceManager.GetString("Label_UniversalObject_TitleYMinPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visibility :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Visibility {
            get {
                return ResourceManager.GetString("Label_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware View Linked Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_WorkStation_HardwareView_LinkedMap {
            get {
                return ResourceManager.GetString("Label_WorkStation_HardwareView_LinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network View Linked Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_WorkStation_NetworkView_LinkedMap {
            get {
                return ResourceManager.GetString("Label_WorkStation_NetworkView_LinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Saved Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_WorkStation_SavedSearch {
            get {
                return ResourceManager.GetString("Label_WorkStation_SavedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search View URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_WorkStation_SearchView_URL {
            get {
                return ResourceManager.GetString("Label_WorkStation_SearchView_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software View Linked Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_WorkStation_SoftwareView_LinkedMap {
            get {
                return ResourceManager.GetString("Label_WorkStation_SoftwareView_LinkedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_Image_Color {
            get {
                return ResourceManager.GetString("Lable_Image_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_Image_ImageName {
            get {
                return ResourceManager.GetString("Lable_Image_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_Image_Name {
            get {
                return ResourceManager.GetString("Lable_Image_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_Image_Opacity {
            get {
                return ResourceManager.GetString("Lable_Image_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lable_Line_Name {
            get {
                return ResourceManager.GetString("Lable_Line_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Splunk_ComboBox_IntervalUnit_Basic {
            get {
                return ResourceManager.GetString("Splunk_ComboBox_IntervalUnit_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hours과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Splunk_ComboBox_IntervalUnit_Hours {
            get {
                return ResourceManager.GetString("Splunk_ComboBox_IntervalUnit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minutes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Splunk_ComboBox_IntervalUnit_Minutes {
            get {
                return ResourceManager.GetString("Splunk_ComboBox_IntervalUnit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Splunk_ComboBox_IntervalUnit_Seconds {
            get {
                return ResourceManager.GetString("Splunk_ComboBox_IntervalUnit_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SplunkArgument_DataGrid_Header_Name {
            get {
                return ResourceManager.GetString("SplunkArgument_DataGrid_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SplunkArgument_DataGrid_Header_Value {
            get {
                return ResourceManager.GetString("SplunkArgument_DataGrid_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CameraIcon {
            get {
                return ResourceManager.GetString("Title_CameraIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LABEL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CameraLabel {
            get {
                return ResourceManager.GetString("Title_CameraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CameraPreset {
            get {
                return ResourceManager.GetString("Title_CameraPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CameraVideo {
            get {
                return ResourceManager.GetString("Title_CameraVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Image {
            get {
                return ResourceManager.GetString("Title_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Line {
            get {
                return ResourceManager.GetString("Title_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_LinkZone {
            get {
                return ResourceManager.GetString("Title_LinkZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Place {
            get {
                return ResourceManager.GetString("Title_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Splunk {
            get {
                return ResourceManager.GetString("Title_Splunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Text {
            get {
                return ResourceManager.GetString("Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROPERTY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_UniversalObject {
            get {
                return ResourceManager.GetString("Title_UniversalObject", resourceCulture);
            }
        }
    }
}
